; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define SrcDir "D:\project\cubeice"
#define MyAppName "CubeICE"
#define MyAppVersion "0.6.1"
#define MyAppPublisher "CubeSoft"
#define MyAppURL "http://www.cube-soft.jp/cubeice/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{ACBED474-AC24-4AC1-B83F-81264814AEB1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputBaseFilename=cubeice-setup
SetupIconFile={#SrcDir}\release\cubeice.ico
Compression=lzma
SolidCompression=true
OutputDir={#SrcDir}
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany=CubeSoft
VersionInfoDescription=CubeICE
VersionInfoCopyright=Copyright (c) 2010 CubeSoft
VersionInfoProductName=CubeICE
AppVerName={#MyAppName} {#MyAppVersion}É¿
WizardImageFile={#SrcDir}\..\common\cubesoft-large.bmp
WizardSmallImageFile={#SrcDir}\..\common\cubesoft-small.bmp

[Languages]
Name: japanese; MessagesFile: compiler:Languages\Japanese.isl
[Files]
Source: {#SrcDir}\cubeice-setup-x86.exe; Flags: dontcopy 32bit
Source: {#SrcDir}\cubeice-setup-x64.exe; Flags: dontcopy 64bit
[Code]
// ------------------------------------------------------------------------- //
//  InitializeSetup
// ------------------------------------------------------------------------- //
function InitializeSetup(): Boolean;
var
    ErrCode: Integer;
begin
	if (IsWin64) then begin
		ExtractTemporaryFile('cubeice-setup-x64.exe');
		if (WizardSilent) then Exec(ExpandConstant('{tmp}\cubeice-setup-x64.exe'), '/VERYSILENT', '', SW_SHOW, ewNoWait, ErrCode)
		else Exec(ExpandConstant('{tmp}\cubeice-setup-x64.exe'), '', '', SW_SHOW, ewNoWait, ErrCode);
	end else begin
		ExtractTemporaryFile('cubeice-setup-x86.exe');
		if (WizardSilent) then Exec(ExpandConstant('{tmp}\cubeice-setup-x86.exe'), '/VERYSILENT', '', SW_SHOW, ewNoWait, ErrCode)
		else Exec(ExpandConstant('{tmp}\cubeice-setup-x86.exe'), '', '', SW_SHOW, ewNoWait, ErrCode);
	end;
	Result := False;
end;
